# Generated by Django 5.1.2 on 2025-02-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_class_teacher_alter_class_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_active',
        ),
        migrations.AddField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(related_name='subject_classes', to='core.class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(related_name='class_subjects', to='core.subject'),
        ),
    ]
