# Generated by Django 5.1.2 on 2025-02-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_subject_is_active_subject_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent_set', to='core.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='student_set', to='core.parent'),
        ),
    ]
